In [2]:
import numpy as np

Array de 1 dimensión

In [28]:
np.array([10, 20, 30, 40, 50, 60])

array([10, 20, 30, 40, 50, 60])

Array de 2 dimensiones

In [27]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array de 3 dimensiones

In [26]:
np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Matriz de 0's

In [ ]:
np.zeros((3, 3)) # Matriz de ceros de 3x3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Matriz de 1's

In [ ]:
np.ones((3, 3)) # Matriz de unos de 3x3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Crear una matriz con un valor especifico

In [ ]:
np.full((3, 3), 8) # Crear una matriz 3x3 llena del valor 8

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

Crear una matriz vacía

In [24]:
np.empty((2, 3)) # Crear una matriz vacía de 2x3

array([[0., 0., 0.],
       [0., 0., 0.]])

Crear un array con un rango específico

In [ ]:
np.arange(0, 10, 2) # Similar a la función range() de Python

array([0, 2, 4, 6, 8])

Crear una secuencia de valores equiespaciados desde un número inicial hasta el número final.

In [22]:
np.linspace(0, 1, 5, endpoint= True, retstep= True) # Crear una secuencia de valores equiespaciados desde un número inicial hasta el número final.

(array([0.  , 0.25, 0.5 , 0.75, 1.  ]), np.float64(0.25))

Crear una matriz aleatoria entre los valores 0 y 1

In [23]:
np.random.rand(3, 4) # Matriz 3x4 con valores aleatorios entre 0 y 1

array([[0.91782106, 0.1302879 , 0.4627246 , 0.99590887],
       [0.17773124, 0.44377174, 0.74733771, 0.44971629],
       [0.92590661, 0.98837613, 0.20940034, 0.87205952]])