In [12]:
import numpy as np

Array de 1 dimensión

In [2]:
np.array([10, 20, 30, 40, 50, 60])

array([10, 20, 30, 40, 50, 60])

Array de 2 dimensiones

In [3]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array de 3 dimensiones

In [4]:
np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Matriz de 0's

In [5]:
np.zeros((3, 3)) # Matriz de ceros de 3x3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Matriz de 1's

In [6]:
np.ones((3, 3)) # Matriz de unos de 3x3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Crear una matriz con un valor especifico

In [7]:
np.full((3, 3), 8) # Crear una matriz 3x3 llena del valor 8

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

Crear una matriz vacía

In [8]:
np.empty((2, 3)) # Crear una matriz vacía de 2x3

array([[7.67112743e+170, 9.05167251e+223, 6.97724295e+228],
       [6.02661079e+175, 2.46090531e-154, 9.91743091e+260]])

Crear un array con un rango específico

In [9]:
np.arange(0, 10, 2) # Similar a la función range() de Python

array([0, 2, 4, 6, 8])

Crear una secuencia de valores equiespaciados desde un número inicial hasta el número final.

In [10]:
np.linspace(0, 1, 5, endpoint= True, retstep= True) # Crear una secuencia de valores equiespaciados desde un número inicial hasta el número final.

(array([0.  , 0.25, 0.5 , 0.75, 1.  ]), np.float64(0.25))

Crear una matriz aleatoria entre los valores 0 y 1

In [11]:
np.random.rand(3, 4) # Matriz 3x4 con valores aleatorios entre 0 y 1

array([[0.08862677, 0.15150701, 0.38939417, 0.80955527],
       [0.32391614, 0.14454305, 0.33800308, 0.89168657],
       [0.1724074 , 0.89811192, 0.16553547, 0.56366487]])