In [2]:
import numpy as np

Dimensiones en los Arrays

In [11]:
# Dimensión del array = 0
arr = np.array('10')
print(arr)

10


In [9]:
# Dimensión del array = 1
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [12]:
# Dimensión del array = 2
arr = np.array([[10, 20, 30], [40, 50, 60]])
arr

array([[10, 20, 30],
       [40, 50, 60]])

In [14]:
# Dimensión del array = 3
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[10, 20, 30], [40, 50, 60]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 20, 30],
        [40, 50, 60]]])

Tipo de dato de un array

In [4]:
arr = np.array([1, 2, 3, 4])
arr.dtype

dtype('int64')

Numero de dimensiones

In [16]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(f"El número de dimensiones del array es:" ,a.ndim)
print(f"El número de dimensiones del array es:" ,b.ndim)
print(f"El número de dimensiones del array es:" ,c.ndim)
print(f"El número de dimensiones del array es:" ,d.ndim)

El número de dimensiones del array es: 0
El número de dimensiones del array es: 1
El número de dimensiones del array es: 2
El número de dimensiones del array es: 3


Definir número de dimensiones

In [17]:
arr = np.array([1, 2, 3, 4, 5], ndmin=5)
print(arr)
print('Número de dimensiones del array:', arr.ndim)

[[[[[1 2 3 4 5]]]]]
Número de dimensiones del array: 5


Forma de un array

In [22]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr.shape

(2, 4)

Total de elementos de un array

In [35]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr.size

8

Información general de un array

In [18]:
np.info(arr)

class:  ndarray
shape:  (1, 1, 1, 1, 5)
strides:  (40, 40, 40, 40, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x1a3f0e9ede0
byteorder:  little
byteswap:  False
type: int64
